name: Update NASA APOD

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/nasa-apod-readme-workflow@v0.2.1
        with:
          api_key: "SheZoCRw1pgRU1m2q7ctTIwVcm0DthI4vMbCAYyS"
